import { chromium } from 'playwright';
import { readFile, mkdir, cp, mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
const temporary = await mkdtemp(join(tmpdir(), 'form-filler-check-'));
const extension = join(temporary, 'extension');
await cp(resolve('extension'), extension, { recursive: true });
const manifest = JSON.parse(await readFile(join(extension, 'manifest.json'), 'utf8'));
manifest.host_permissions.push('https://portfolio.test/*', 'https://forms.test/*', 'https://api.github.com/*');
await writeFile(join(extension, 'manifest.json'), JSON.stringify(manifest));
await mkdir('artifacts', { recursive: true });
const profileHtml = await readFile('fixtures/profile.html', 'utf8');
const formHtml = await readFile('fixtures/form.html', 'utf8');
const context = await chromium.launchPersistentContext(join(temporary, 'profile'), { channel: 'chromium', headless: true, colorScheme: 'light', viewport: { width: 1440, height: 1100 }, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
let apiStatus = 200;
let requests = 0;
try {
  await context.route('https://portfolio.test/**', async route => {
    const path = new URL(route.request().url()).pathname;
    if (path === '/robots.txt') return route.fulfill({ contentType: 'text/plain', body: 'Sitemap: https://portfolio.test/sitemap.xml' });
    if (path === '/sitemap.xml') return route.fulfill({ contentType: 'application/xml', body: '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://portfolio.test/pages.xml</loc></sitemap><sitemap><loc>https://elsewhere.test/private.xml</loc></sitemap></sitemapindex>' });
    if (path === '/pages.xml') return route.fulfill({ contentType: 'application/xml', body: '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://portfolio.test/</loc></url><url><loc>https://portfolio.test/work</loc></url><url><loc>https://elsewhere.test/private</loc></url></urlset>' });
    return route.fulfill({ contentType: 'text/html', body: profileHtml });
  });
  await context.route('https://forms.test/**', route => route.fulfill({ contentType: 'text/html', body: formHtml }));
  await context.route('https://api.github.com/users/alex-example/repos?*', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify([{ name: 'canvas-kit', description: 'Accessible components for creative tools', language: 'TypeScript', html_url: 'https://github.com/alex-example/canvas-kit', fork: false }]) }));
  await context.route('https://api.github.com/users/alex-example', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ name: 'Alex Morgan', bio: 'Product engineer building accessible web tools.', company: 'Northstar Studio', location: 'London', html_url: 'https://github.com/alex-example', blog: 'https://portfolio.test/' }) }));
  await context.route('https://api.typesafe.ai/v1/systemone', async route => {
    requests++;
    assert.equal(route.request().headers().authorization, 'Bearer synthetic-test-key');
    if (apiStatus !== 200) return route.fulfill({ status: apiStatus, body: '{}' });
    const body = route.request().postDataJSON();
    assert.equal(body.model, 'jev-1.13.0');
    const answers = {};
    for (const [key, question] of Object.entries(body.questions)) {
      let choice = 'skip';
      if (typeof question.instructions === 'string') {
        const field = question.instructions.match(/^Select the exact (.*?) of the profile owner/)[1];
        const kind = { 'Full name': 'name', 'Email address': 'email', 'Phone number': 'phone', Location: 'location', 'Job title': 'role', 'Current company': 'company', 'Company website URL': 'companyWebsite', 'Portfolio URL': 'website', 'LinkedIn URL': 'linkedin', 'X / Twitter URL': 'twitter', 'GitHub URL': 'github', 'About you': 'bio', Skills: 'skills' }[field];
        choice = Object.entries(question.criteria).find(([, candidate]) => candidate.kind === kind)?.[0] || 'skip';
      } else {
        const label = question.instructions.field.toLowerCase();
        const desired = label.includes('name') ? 'Alex Morgan' : label.includes('email') ? 'alex@example.test' : label.includes('location') ? 'London' : label.includes('about') ? 'I build accessible web products and open-source developer tools.' : label.includes('company') ? 'Northstar Studio' : null;
        choice = Object.entries(question.criteria).find(([, candidate]) => typeof candidate === 'object' && candidate.value === desired)?.[0] || 'skip';
      }
      answers[key] = { choice, confidence: .98 };
    }
    return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ answers }) });
  });
  const worker = context.serviceWorkers()[0] || await context.waitForEvent('serviceworker');
  const id = new URL(worker.url()).host;
  const form = await context.newPage();
  await form.goto('https://forms.test/apply');
  const tabId = await worker.evaluate(async () => (await chrome.tabs.query({ url: 'https://forms.test/*' }))[0].id);
  const app = await context.newPage();
  const errors = [];
  app.on('pageerror', error => errors.push(error.message));
  await app.goto(`chrome-extension://${id}/app.html?tab=${tabId}`);
  await app.getByRole('button', { name: 'Settings', exact: false }).click();
  await app.locator('#api-key').fill('synthetic-test-key');
  await app.getByRole('button', { name: 'Save key', exact: true }).click();
  await app.getByText('API key saved on this device. Reload both Jev extensions to connect key sharing.', { exact: true }).waitFor();
  assert.equal(await app.locator('#api-key').inputValue(), '');
  await app.getByRole('button', { name: 'Save key', exact: true }).click();
  await app.getByText('Existing key kept.', { exact: true }).waitFor();
  assert.equal((await worker.evaluate(() => chrome.storage.local.get('apiKey'))).apiKey, 'synthetic-test-key');
  await app.getByRole('button', { name: 'Sources', exact: false }).first().click();
  await app.locator('[data-connector="website"]').click();
  await app.locator('#source-url').fill('https://portfolio.test/');
  await app.locator('#crawl').check();
  await app.locator('#connect-source').click();
  await app.locator('#discovery').waitFor();
  assert.equal(await app.locator('#discovered-pages input').count(), 2);
  await app.locator('#import-selected').click();
  await app.getByText('2 pages imported. Ready to build your profile.', { exact: true }).waitFor();
  assert.equal(await app.locator('.source-row').count(), 2);
  await app.locator('[data-connector="github"]').click();
  await app.locator('#source-url').fill('https://github.com/alex-example');
  await app.locator('#connect-source').click();
  await app.getByText('Source imported. Build your profile when you’re ready.', { exact: true }).waitFor();
  assert.equal(await app.locator('.source-row').count(), 3);
  await app.locator('#build-profile').click();
  await app.locator('#draft-notice').waitFor();
  assert.equal(await app.locator('#profile-name').inputValue(), 'Alex Morgan');
  assert.equal(await app.locator('#profile-email').inputValue(), 'alex@example.test');
  await app.getByRole('button', { name: 'Save profile', exact: true }).click();
  await app.getByText('Profile saved on this device. Ready for your next form.', { exact: true }).waitFor();
  await app.locator('[data-view="fill"]').click();
  await app.locator('#scan').click();
  await app.locator('#apply').waitFor();
  assert.equal(await app.locator('.answer-card').count(), 5);
  assert.equal(await app.locator('[data-answer]:checked').count(), 4);
  assert.equal(await app.locator('.answer-card label').nth(2).textContent(), 'LocationSource-backed suggestion');
  await app.locator('#dismiss-status').click();
  await app.screenshot({ animations: 'disabled', path: 'artifacts/answer-review.png', fullPage: true });
  await app.locator('#apply').click();
  await app.getByText('4 fields filled. 0 skipped. Nothing was submitted.', { exact: true }).waitFor();
  assert.equal(await form.locator('[name="name"]').inputValue(), 'Alex Morgan');
  assert.equal(await form.locator('[name="email"]').inputValue(), 'alex@example.test');
  assert.equal(await form.locator('[name="location"]').inputValue(), 'london');
  assert.equal(await form.locator('[name="company"]').inputValue(), 'Keep my existing company');
  assert.equal(await form.locator('[name="password"]').inputValue(), '');
  assert.equal(await form.evaluate(() => window.submissions), 0);
  await form.screenshot({ path: 'artifacts/filled-form.png', fullPage: true });
  await form.locator('[name="name"]').fill('Edited after filling');
  await app.locator('#undo').click();
  await app.getByText('Restored 3 fields. Any values you edited afterward were left alone.', { exact: true }).waitFor();
  assert.equal(await form.locator('[name="name"]').inputValue(), 'Edited after filling');
  assert.equal(await form.locator('[name="email"]').inputValue(), '');
  await form.locator('[name="name"]').fill('');
  await app.locator('#scan').click();
  await app.locator('#apply').waitFor();
  await form.locator('[name="email"]').fill('changed@example.test');
  await app.locator('#apply').click();
  await app.getByText(/3 fields filled. 1 skipped/).waitFor();
  assert.equal(await form.locator('[name="email"]').inputValue(), 'changed@example.test');
  apiStatus = 401;
  await app.locator('#scan').click();
  await app.getByText('TypeSafe rejected your API key. Replace it in Settings.', { exact: true }).waitFor();
  assert.equal(await app.locator('#apply').isHidden(), true);
  apiStatus = 200;
  await app.locator('[data-view="sources"]').click();
  await app.locator('#status-bar').evaluate(node => node.hidden = true);
  await app.screenshot({ animations: 'disabled', path: 'artifacts/workspace.png', fullPage: true });
  await app.emulateMedia({ colorScheme: 'dark' });
  await app.waitForFunction(() => getComputedStyle(document.documentElement).colorScheme === 'dark');
  assert.equal(await app.evaluate(() => getComputedStyle(document.body).backgroundColor), 'rgb(25, 23, 30)');
  await app.waitForFunction(() => getComputedStyle(document.querySelector('.connector')).backgroundColor === 'rgb(35, 31, 42)');
  await app.screenshot({ animations: 'disabled', path: 'artifacts/workspace-dark.png', fullPage: true });
  await app.locator('[data-connector="website"]').click();
  assert.equal(await app.locator('#source-dialog').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(35, 31, 42)');
  await app.screenshot({ animations: 'disabled', path: 'artifacts/source-dialog-dark.png', fullPage: true });
  await app.locator('#close-dialog').click();
  await app.locator('[data-view="settings"]').click();
  assert.equal(await app.locator('#api-key').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(28, 25, 34)');
  await app.screenshot({ animations: 'disabled', path: 'artifacts/settings-dark.png', fullPage: true });
  await app.emulateMedia({ colorScheme: 'light' });
  await app.waitForFunction(() => getComputedStyle(document.documentElement).colorScheme === 'light');
  assert.equal(await app.evaluate(() => getComputedStyle(document.body).backgroundColor), 'rgb(250, 250, 251)');
  await app.locator('[data-view="sources"]').click();
  await app.setViewportSize({ width: 700, height: 1050 });
  await app.screenshot({ animations: 'disabled', path: 'artifacts/workspace-narrow.png', fullPage: true });
  assert.equal(await app.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await app.setViewportSize({ width: 1440, height: 1100 });
  const checks = await app.evaluate(async () => {
    const { parseHtml, sitemapEntries } = await import('./sources.js');
    const parsed = parseHtml('<html><head><title>Fixture</title></head><body><h1>Alex</h1><form><p>PRIVATE FORM CONTENT</p></form><script>globalThis.injected=true</script><p>Public profile text</p></body></html>', 'https://portfolio.test/');
    return { candidates: parsed.candidates, injected: Boolean(globalThis.injected), sitemap: sitemapEntries('<urlset><url><loc>javascript:alert(1)</loc></url><url><loc>https://other.test/</loc></url><url><loc>https://portfolio.test/about</loc></url></urlset>', 'https://portfolio.test') };
  });
  assert.equal(JSON.stringify(checks.candidates).includes('PRIVATE FORM CONTENT'), false);
  assert.equal(checks.injected, false);
  assert.deepEqual(checks.sitemap.urls, ['https://portfolio.test/about']);
  const retrievalHtml = await readFile('fixtures/portfolio-retrieval.html', 'utf8');
  const extracted = await app.evaluate(async html => {
    const { parseHtml } = await import('./sources.js');
    return parseHtml(html, 'https://portfolio.test/');
  }, retrievalHtml);
  const values = kind => extracted.candidates.filter(item => item.kind === kind).map(item => item.value);
  assert.ok(values('name').includes('Alex Morgan'));
  assert.ok(values('twitter').includes('https://x.com/alex_example'));
  assert.ok(values('linkedin').includes('https://www.linkedin.com/in/alex-example/'));
  assert.ok(values('email').includes('alex@example.test'));
  assert.ok(values('company').includes('Brightwave.ai'));
  assert.ok(values('companyWebsite').includes('https://brightwave.test/'));
  assert.ok(extracted.candidates.some(item => item.kind === 'company' && item.value === 'Brightwave.ai' && item.current));
  assert.equal(extracted.candidates.some(item => item.kind === 'company' && item.value === 'Old Studio' && item.current), false);
  assert.ok(extracted.candidates.some(item => item.kind === 'role' && item.value === 'Software Engineer' && item.current));
  assert.equal(await app.evaluate(async () => {
    const { parseHtml } = await import('./sources.js');
    try { parseHtml('<title>Checking your browser - reCAPTCHA</title><h1>Please wait</h1>', 'https://profile.test/'); return false; } catch { return true; }
  }), true);
  await app.locator('#refresh-sources').click();
  await app.getByText('3 sources refreshed. Build your profile to use the recovered context.', { exact: true }).waitFor();

  await form.goto('https://portfolio.test/');
  await app.locator('#import-open').click();
  await app.getByText('Open page imported. Build your profile to review its details.', { exact: true }).waitFor();
  const savedSources = await worker.evaluate(() => chrome.storage.local.get('sources'));
  assert.equal(JSON.stringify(savedSources).includes('Do not import form contents'), false);
  assert.equal(JSON.stringify(savedSources).includes('private field value'), false);
  await app.locator('[data-view="settings"]').click();
  await app.locator('#remove-key').click();
  await app.getByText('API key removed.', { exact: true }).waitFor();
  assert.equal((await worker.evaluate(() => chrome.storage.local.get('apiKey'))).apiKey, undefined);
  assert.deepEqual(errors, []);
  assert.ok(requests >= 4);
  console.log('PASS: installed extension, key storage, GitHub import, nested sitemap discovery, profile extraction, answer review, safe filling, undo, stale fields, invalid API key, mobile layout, and untrusted HTML isolation.');
} finally {
  await context.close();
  await rm(temporary, { recursive: true, force: true });
}
